// src/lib/button.svelte
<script>
	import clsx from 'clsx';

	export let variant = 'primary';
	export let classes = '';
</script>

<button
	class={clsx(
		'py-2 px-5 rounded-full border border-primary font-medium font-open-sans',
		variant === 'primary' && 'bg-primary text-white',
		variant === 'outline' && 'border-primary text-gray-950',
        classes
	)}
>
	<slot />
</button>

// src/components/Button.tsx
import React from "react";
import clsx from "clsx";

interface ButtonProps {
  variant?: "primary" | "outline";
  className?: string;
  children: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  variant = "primary",
  className,
  children,
}) => {
  return (
    <button
      className={clsx(
        "border-primary-100 font-open-sans rounded-full border px-5 py-3 font-semibold",
        variant === "primary" && "bg-primary-100 text-white",
        variant === "outline" && "text-gray-950",
        className
      )}
    >
      {children}
    </button>
  );
};
