// src/lib/linkButton.svelte
<script>
	import clsx from 'clsx';

	export let variant = 'primary';
	export let classes = '';
	export let href = '/';
</script>

<a
	class={clsx(
		'py-3 px-5 rounded-full border border-primary-100 font-semibold font-open-sans',
		variant === 'primary' && 'bg-primary-100 text-white',
		variant === 'outline' && 'text-gray-950',
		classes
	)}
	{href}
>
	<slot />
</a>

// src/components/LinkButton.tsx
import Link from "next/link";
import React from "react";
import clsx from "clsx";

interface LinkButtonProps {
  variant?: "primary" | "outline";
  classes?: string;
  children: React.ReactNode;
  href: string;
}

export const LinkButton: React.FC<LinkButtonProps> = ({
  variant = "primary",
  classes,
  children,
  href,
}) => {
  return (
    <Link
      className={clsx(
        "border-primary-100 font-open-sans rounded-full border px-5 py-3 font-semibold",
        variant === "primary" && "bg-primary-100 text-white",
        variant === "outline" && "text-gray-950",
        classes
      )}
      href={href}
    >
      {children}
    </Link>
  );
};
