// src/lib/services.svelte
<script>
	import manCleaningFloorImg from './assets/home/man-cleaning-wall.png';
	import ladyCleaningMat from './assets/home/lady-cleaning-mat.png';
	import womanCleaningFloor from './assets/home/lady-cleaning-floor.png';
	import womanCleaningFloorTwo from './assets/home/lady-cleaning-floor-2.png';

	const services = [
		{
			imgUrl: manCleaningFloorImg,
			title: 'Janitorial/General Cleaning service'
		},
		{
			imgUrl: ladyCleaningMat,
			title: 'Carpet & Upholstery Cleaning'
		},
		{
			imgUrl: womanCleaningFloor,
			title: 'Industrial Cleaning'
		},
		{
			imgUrl: womanCleaningFloorTwo,
			title: 'Floor restoration & Cleaning'
		}
	];
</script>

<section class="flex flex-wrap gap-5 mt-12 justify-center">
	{#each services as service}
		<div
			style="background-image: url('{service.imgUrl}')"
			class="h-[448px] flex-1 rounded-3xl bg-cover relative text-white"
		>
			<div class="absolute rounded-3xl inset-0 bg-opacity-40 bg-[#544b4b]" />
			<div class="relative z-10 mt-[320px] px-6">
				<p>Cleaning | On Demand</p>
				<h2 class="font-bold text-2xl">{service.title}</h2>
			</div>
		</div>
	{/each}
</section>

// src/components/Services.tsx
import React from "react";

const services = [
  {
    imgUrl: "/assets/home/man-cleaning-wall.png",
    title: "Janitorial/General Cleaning service",
  },
  {
    imgUrl: "/assets/home/lady-cleaning-mat.png",
    title: "Carpet & Upholstery Cleaning",
  },
  {
    imgUrl: "/assets/home/lady-cleaning-floor.png",
    title: "Industrial Cleaning",
  },
  {
    imgUrl: "/assets/home/lady-cleaning-floor-2.png",
    title: "Floor restoration & Cleaning",
  },
];

export const Services = () => {
  return (
    <section className="mt-12 flex flex-wrap justify-center gap-5">
      {services.map((service) => (
        <div
          key={service.title}
          style={{ backgroundImage: `url(${service.imgUrl})` }}
          className="relative h-[448px] flex-1 rounded-3xl bg-cover text-white"
        >
          <div className="absolute inset-0 rounded-3xl bg-[#544b4b] bg-opacity-40" />
          <div className="relative z-10 mt-[320px] px-6">
            <p>Cleaning | On Demand</p>
            <h2 className="text-2xl font-bold">{service.title}</h2>
          </div>
        </div>
      ))}
    </section>
  );
};
