// src/lib/title.svelte
<script>
    import clsx from 'clsx'
	export let classes = '';
	export let subTitle = '';
</script>

<div class={clsx("text-gray-950 text-center max-w-3xl mx-auto", classes)}>
	<h3 class="font-semibold text-4xl font-lato">
		<slot />
	</h3>
	{#if subTitle}
		<p class="font-open-sans mt-2">{subTitle}</p>
	{/if}
</div>

// src/components/Title.tsx
import React from 'react';
import clsx from 'clsx';

interface TitleProps {
  classes?: string;
  subTitle?: string;
  children: React.ReactNode;
}

export const Title: React.FC<TitleProps> = ({ classes, subTitle, children }) => {
  return (
    <div className={clsx('mx-auto max-w-3xl text-center text-gray-950', classes)}>
      <h3 className="font-lato text-3xl font-semibold sm:text-4xl">{children}</h3>
      {subTitle && <p className="mt-2 font-open-sans">{subTitle}</p>}
    </div>
  );
};
